version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    ports:
      - "5000:5000"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - chatnetwork
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "chatmysql:/var/lib/mysql"
    networks:
      - chatnetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    ports:
      - "8080:80"
    environment:
      MYSQL_USERNAME: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PMA_HOST: "mysql"
    networks:
      - chatnetwork
    depends_on:
      - mysql

networks:
  chatnetwork:
    driver: bridge

volumes:
  chatmysql:
    driver: local
